config/routes.rb
Rails.application.routes.draw do
  get 'answers/index'
  get 'answers/new'
  namespace :admin do
    get "/dashboard", to: 'pages#home'
    resources :users, only: [:index, :update, :destroy]
    resources :categories do 
      resources :words
    end
  end
  root "pages#home"
  get '/about', to:'pages#about'
  get '/contact', to:'pages#contact'
  resources :users
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'
  
  resources :sessions, only: :create
  resources :lessons do
    resources :answers
  end
  resources :users do
    member do
      get :following, :followers, :words_learned
    end
  end
  
  resources :relationships, only: [:create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/share/_admin_side.html.erb
<div class="card-header">
  Dashboard
</div>
<ul class="list-group list-group-flush">
  <li class="list-group-item">
    <%= link_to "Users", admin_users_path, class: "btn btn-sm btn-link" %>
  </li>
  <li class="list-group-item">
    <%= link_to "Categories", admin_categories_path, class: "btn btn-sm btn-link" %>
  </li>
</ul>

app/views/share/_error_message.html.erb
<% if object.errors.any? %> 
    <p><%= pluralize(object.errors.count, "error") %></p>
    <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>

app/views/share/_flash_message.html.erb
<% flash.each do |type, message| %>
    <div class="alert alert-<%= type %> alert-dismissible" role="alert">
        <%= message %>
    </div>
<% end %>

app/views/share/_form.html.erb
<%= form_with(model:@user, local:true) do |f| %>
    <%= render "share/error_message" %>
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control mb-2", placeholder: "Enter Name" %>
    <%= f.label :email %>
    <%= f.email_field :email, class: "form-control mb-2", placeholder: "Enter Email" %>
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control mb-2", placeholder: "Enter Password" %>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: "form-control mb-4", placeholder: "Confirm Password" %>
    <%= f.submit submit_name,class:"btn btn-primary btn-block",placeholder:"Create an account" %>
<% end %>

app/views/share/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
    <div class="container">
        <a class="navbar-brand" href="#">Els</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse navbar-nav" id="navbarNavDropdown">
            <div class="mr-auto"></div>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <%= link_to "Home",root_path,class:"nav-link"  %>
                </li>
                <li class="nav-item">
                <%= link_to "About",about_path,class:"nav-link"  %>
                </li>
                <li class="nav-item">
                    <%= link_to "Contact",contact_path,class:"nav-link"  %>
                </li>
            <% if logged_in? %>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
                <i class="fas fa-user"></i><%= current_user.name %>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to "Edit",edit_user_path(current_user),class:"dropdown-item" %>
                <%= link_to "User List",users_path,class:"dropdown-item"  %>
                <%= link_to "profile",user_path(current_user),class:"dropdown-item"  %>
                <%= link_to "Lessons",lessons_path,class:"dropdown-item"  %>
                <div class="dropdown-divider"></div>
                <%= link_to "logout",logout_path,class:"dropdown-item"  %>
                </div>
            </li>
            <% else %>
            <li class="nav-item">
                <%= link_to "login",login_path,class:"nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "Sign up",signup_path,class:"nav-link"  %>
            </li>
                
            <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/share/_stats.html.erb
<% @user ||=current_user %>
<div class="stats">
    <a href="<%= following_user_path(@user) %>">
		<strong id="following" class="stat">
			<%= @user.following.count %>
		</strong>
      following
    </a>
  <a href="<%= followers_user_path(@user) %>">
		<strong id="following" class="stat">
			<%= @user.followers.count %>
		</strong>
    followers
  </a>
</div>