config/routes.rb
Rails.application.routes.draw do
  get 'answers/index'
  get 'answers/new'
  namespace :admin do
    get "/dashboard", to: 'pages#home'
    resources :users, only: [:index, :update, :destroy]
    resources :categories do 
      resources :words
    end
  end
  root "pages#home"
  get '/about', to:'pages#about'
  get '/contact', to:'pages#contact'
  resources :users
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'
  
  resources :sessions, only: :create
  resources :lessons do
    resources :answers
  end
  resources :users do
    member do
      get :following, :followers, :words_learned
    end
  end
  
  resources :relationships, only: [:create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :category
  has_many :choices, dependent: :destroy
  has_many :answers, dependent: :destroy
  accepts_nested_attributes_for :choices
  
  validates :content, presence: true
  validate :only_one_correct_answer
  def correct_answer
    choices.where(correct: true).first
  end
  private
  def only_one_correct_answer
    if choices.select {|choice| choice.correct == true}.count != 1
      errors.add(:choices, ":Please select one correct answer only")
    end
  end
end

app/controllers/admin/words_controller.rb
class Admin::WordsController < ApplicationController
  before_action :admin_user, only: :home
  before_action :logged_in_user
  def index
    @category = Category.find(params[:category_id])
    @words=@category.words.paginate(page: params[:page], per_page: 10).order(created_at: :desc)    
  end
  def new
    @category = Category.find(params[:category_id])
    @word=@category.words.new
    3.times {
      @word.choices.build
    }
  end
  def create
    @category = Category.find(params[:category_id])
    @word=@category.words.new(word_params)
    if @word.save
      flash[:success] = "Successfully Created word"
      redirect_to admin_category_words_path(@category)
     else
      render "new"
     end
  end
  def edit
    @word = Word.find(params[:id])
    @category = Category.find(params[:category_id])
  end
  def update
    @category = Category.find(params[:category_id])
    @word = Word.find(params[:id])
    if @word.update(word_params)
      flash[:success] = "Word Updated"
      redirect_to admin_category_words_path(@category)
    else
      render 'edit'
    end
  end
  def destroy
    @category = Category.find(params[:category_id]);
    @word = @category.words.find(params[:id])
    @word.destroy
    redirect_to admin_category_words_path(@category)
  end
  private
  def word_params
    params.require(:word).permit(:content, choices_attributes: [:id, :content, :correct])
  end
end

app/helpers/admin/words_helper.rb
module Admin::WordsHelper
    
end

app/views/admin/words/_form.html.erb
<%= form_with(model: [:admin, @category, @word], local:true) do |f| %>
    <%= render "share/error_message", object: f.object %>
    <%= f.label :content %>
    <%= f.text_field :content, class: "form-control mb-2", placeholder: "Enter Word" %><hr>
    <%= f.fields_for :choices do |f| %>
        <%= f.text_field :content, class: "form-control mb-2", placeholder: "Enter Choice" %>  
        <div class="check-box">
            <%= f.check_box :correct %>
            Answer
        </div>
    <% end %>
    <%= f.submit submit_name,class:"btn btn-primary btn-block" %>
<% end %>

app/views/admin/words/edit.html.erb
<%provide(:title, 'Edit Word')%>
<div class="col-4 mx-auto">
    <h1 class="text-center mt-4">Edit Word</h1>
    <%= render "form", submit_name:"Save" %>
</div>

app/views/admin/words/index.html.erb
<%= provide(:title,"Word Management") %>
<div class="row">
    <div class="col-2">
        <div class="card">
            <%= render "share/admin_side" %>
        </div>
    </div>
    <div class="col-10">
        <div class="card">
            <div class="card-header" style="justify-content:space-between;display:flex;"><%= @category.title %><%= link_to "New word", new_admin_category_word_path, class: "btn btn-success"%></div>
            <div class="card-body">
                <div class="row">
                    <table class="table">
                        <tr>
                            <th>Word</th>
                            <th>Answer</th>
                            <th>Created at</th>
                            <th>actions</th>
                        </tr>
                        <% @words.each do |word| %>
                            <tr>
                                <td><%= word.content %></td>
                                <td><%= word.choices.find_by(correct: true).content %></td>
                                <td><%= word.created_at.to_date %></td>
                                <td><%= link_to "Edit", edit_admin_category_word_path(id: word), class: "btn btn-success btn-block" %></td>
                                <td><%= link_to "Delete", admin_category_word_path(id: word), method: :delete, class: "btn btn-secondary btn-block" %></td>
                            </tr>
                        <% end %>
                    </table>
                    <div class="mb-3" style="margin:auto;">
                        <%= will_paginate @categories %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/admin/words/new.html.erb
<%= provide(:title,"Create Word") %>
<h1 class="text-center">Create Word</h1>

<div class="row">
    <div class="col-3">
    </div>
    <div class="col-6">
        <%= render "form", submit_name:"Save" %>
    </div>
    <div class="col-3">
    </div>
</div>