config/routes.rb
Rails.application.routes.draw do
  get 'answers/index'
  get 'answers/new'
  namespace :admin do
    get "/dashboard", to: 'pages#home'
    resources :users, only: [:index, :update, :destroy]
    resources :categories do 
      resources :words
    end
  end
  root "pages#home"
  get '/about', to:'pages#about'
  get '/contact', to:'pages#contact'
  resources :users
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'
  
  resources :sessions, only: :create
  resources :lessons do
    resources :answers
  end
  resources :users do
    member do
      get :following, :followers, :words_learned
    end
  end
  
  resources :relationships, only: [:create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_many :lessons, dependent: :destroy
    has_many :answers, through: :lessons
    validates :name, presence: true, length: { maximum: 50 }
    EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 50 },
                        format: { with: EMAIL_REGEX },
                        uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, length: { minimum: 6 }, presence: true
    has_many :active_relationships, foreign_key: "follower_id",
                                    class_name: "Relationship",
                                    dependent: :destroy

    has_many :following, through: :active_relationships, source: :followed
    has_many :passive_relationships, foreign_key: "followed_id",
                                    class_name: "Relationship",
                                    dependent: :destroy
    has_many :followers, through: :passive_relationships, source: :follower
    has_many :activities, dependent: :destroy
    def lesson_taken(category)
        lessons.find_by(category_id: category.id)
    end
    def following?(other_user)
        active_relationships.find_by(followed_id:other_user.id)
    end
    def follow(other_user)
        active_relationships.create!(followed_id: other_user.id)
    end
    def unfollow(other_user)
        active_relationships.find_by(followed_id: other_user.id).destroy
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :admin_user, only: :home
  before_action :logged_in_user
  def index
    @users=User.paginate(page: params[:page], per_page: 10).order(created_at: :desc) 
    @user=User.find_by(params[:id])
  end
  def update
    @user = User.find(params[:id])
    @user.update_attribute(:admin, true)
    redirect_to admin_users_path
  end
  def destroy
    @user= User.find(params[:id])
    @user.update_attribute(:admin, false)
    redirect_to admin_users_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index]
  before_action :correct_user, only: :edit
  def new
    @user=User.new
  end
  def index
    @users = User.paginate(page: params[:page], per_page: 10).order(created_at: :desc)   

  end
  def show
    @user = User.find(params[:id])
    @activity_feeds= @user.activities
  end
  def edit
    @user = User.find(params[:id])
  end
  def create
    @user = User.new(user_params)
     if @user.save
      flash[:success] = "Successfully Created account"
      redirect_to root_url
     else
      render "new"
     end
  end
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Profile Updated"
      redirect_to user_path
    else
      render 'edit'
    end
  end
  def following
    @users = User.find(params[:id])
    @following = @users.following.paginate(page: params[:page], per_page: 10).order(created_at: :desc)
  end
  def followers
    @users = User.find(params[:id])
    @followers = @users.followers.paginate(page: params[:page], per_page: 10).order(created_at: :desc)
  end
  def words_learned
    @user = User.find(params[:id])
    @words = @user.answers.paginate(page: params[:page], per_page: 10).order(created_at: :desc)
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confimation)
    end
    def correct_user
      user=User.find(params[:id])
      if user !=current_user
        flash[:danger]="You are not authorized."
        redirect_to root_url
      end
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user, options = { size: 80 })
        size = options[:size]
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
      end
end

app/views/users/_activity.html.erb
<div class="card">
            <div class="card-header">Activity feeds</div>
            <div class="card-body">
              <% @activity_feeds.each do |activity| %>
                <div class="card">
                    <div class="card-body row">
                    <% if activity.user == current_user
                    user= "You "
                    else 
                    user= activity.user.name
                    end%>
                    
                        <div class="col-2"><%= gravatar_for activity.user, size: 52 %>
                          
                        </div>
                        
                        <div class="col-8">
                            <%= link_to user, user_path(user) %>
                            <% if activity.action_type == "Relationship" %>
                                <% follow = User.find(activity.action_id) %>
                                follow <%= link_to follow.name, follow %>
                            <% else %>
                                <% lesson = Lesson.find(activity.action_id) %>
                                learn <%= lesson.result.to_i %> of <%= lesson.category.words.count %> in <%= link_to lesson.category.title, lesson %>
                            <% end %>
                            <p><%= time_ago_in_words(activity.created_at) %> ago</p>
                        </div>
                    </div>
                </div>
                <% end %>
            </div>
        </div>

app/views/users/_follow.html.erb
<%= form_with(model:current_user.active_relationships.build, local: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless @user== current_user %>
    <div id="follow_form">
        <%if current_user.following?(@user) %>
            <%= render 'unfollow' %>
        <%else%>
            <%= render 'follow' %>
        <%end%>
    </div>
<%end%>

app/views/users/_form.html.erb
<%= form_with(model:@user, local:true) do |f| %>
    <%= render "share/error_message" %>
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control mb-2", placeholder: "Enter Name" %>
    <%= f.label :email %>
    <%= f.email_field :email, class: "form-control mb-2", placeholder: "Enter Email" %>
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control mb-2", placeholder: "Enter Password" %>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: "form-control mb-4", placeholder: "Confirm Password" %>
    <%= f.submit btn_msg,class:"btn btn-primary btn-block",placeholder:"Create an account" %>

<% end %>

app/views/users/_unfollow.html.erb
<%= form_with(model: current_user.active_relationships.find_by(followed_id: @user.id),
             html: {method: :delete},
             local: true) do |f| %>
    <%= f.submit "Unfollow", class: "btn btn-large btn-secondary" %>
<% end %>

app/views/users/edit.html.erb
<%provide(:title, 'Edit Profile')%>
<div class="col-4 mx-auto">
    <h1 class="text-center mt-4">Edit Profile</h1>
    <%= render "form", btn_msg: "Update Profile" %>
</div>

app/views/users/followers.html.erb
<% provide(:title, 'Users') %>
<h2 class="text-center">Followers</h2>
<div class="row">
    <div class="col-2"></div>
    <div class="col-8">
        <ul class="list-group">
            <div class="mb-3" style="margin:auto;">
                <%#= will_paginate @users %>
                <%= will_paginate @followers %>
            </div>
            <% @followers.each do |user| %>
                <li style="list-style:none;" class="list-group-item">
                    <%= gravatar_for user, size: 52 %>
                    <%= link_to user.name, user_path(user) %>
                </li>  
            <% end %>
            <div class="mt-3" style="margin:auto;">
                <%#= will_paginate @users %>
                <%= will_paginate @followers %>
            </div>
        </ul>
    </div>
    <div class="col-2"></div>
</div>

app/views/users/following.html.erb
<% provide(:title, 'Users') %>
<h2 class="text-center">Followings</h2>
<div class="row">
    <div class="col-2"></div>
    <div class="col-8">
        <ul class="list-group">
            <div class="mb-3" style="margin:auto;">
                <%#= will_paginate @users %>
                <%= will_paginate @following %>
            </div>
            <% @following.each do |user| %>
                <li style="list-style:none;" class="list-group-item">
                    <%= gravatar_for user, size: 52 %>
                    <%= link_to user.name, user_path(user) %>
                </li>  
            <% end %>
            <div class="mt-3" style="margin:auto;">
                <%#= will_paginate @users %>
                <%= will_paginate @following %>
            </div>
        </ul>
    </div>
    <div class="col-2"></div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Users') %>
<h2 class="text-center">User List</h2>
<div class="row">
    <div cla    ss="col-2"></div>
    <div class="col-8">
        <ul class="list-group">
            <div class="mb-3" style="margin:auto;">
                <%= will_paginate @users %>
            </div>
            <% @users.each do |user| %>
                <li style="list-style:none;" class="list-group-item">
                    <%= gravatar_for user, size: 52 %>
                    <%= link_to user.name, user_path(user) %>
                </li>  
            <% end %>
            <div class="mt-3" style="margin:auto;">
                <%= will_paginate @users %>
            </div>
        </ul>
    </div>
    <div class="col-2"></div>
</div>

app/views/users/new.html.erb
<%= provide(:title,"Sign up") %>
<h1 class="text-center">Signup</h1>
<h4 class="text-center">join us free</h4>
<div class="row">
    <div class="col-3">
    </div>
    <div class="col-6">
        <%= render "share/form", submit_name:"Submit" %>
    </div>
    <div class="col-3">
    </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
<div class="card col-4">
    <div class="card-header">User-Information</div>
    <div class="card-body text-center">
        <%= gravatar_for(@user, size: 200) %>
        <h4 class="card-text text-center"><%= @user.name %></h4>
        <p class="text-center"><%= @user.email %></p> 

        <%= render 'share/stats' %>

        <%= render 'follow_form' if logged_in? %>


        <% if @user.admin == true %>
            <%= link_to "Admin dashboad", admin_dashboard_path, class: "btn btn-success btn-block"%> 
        <% end %>
        <%= link_to "words learned", words_learned_user_path(@user)%>
    </div>
</div>
<div class="col-8">
    <%= render "activity" %>
</div>
</div>

app/views/users/words_learned.html.erb
<h1 class="text-center mb-3">Words_learned</h1>
<table class="table">
	<thead class="thead-light">
		<tr>
			<th scope="col">Word</th>
			<th scope="col">Choice</th>
			<th scope="col">Correct</th>
			<th scope="col">Mark</th>
		</tr>
	</thead>
	<tbody>
        <div class="mt-3" style="margin:auto;width:max-content;">
                <%= will_paginate @words %>
            </div>
		<% @words.each do |answer| %>
				<tr>
					<td><%= answer.word.content %></td>
					<td><%= answer.choice.content  %></td>
					<td><%= answer.word.correct_answer.content  %></td>
					<td><%= icon(answer.choice, answer.word.correct_answer) %></td>
				</tr>
            
		<%end%>
        
	</tbody>
</table>