config/routes.rb
Rails.application.routes.draw do
  get 'answers/index'
  get 'answers/new'
  namespace :admin do
    get "/dashboard", to: 'pages#home'
    resources :users, only: [:index, :update, :destroy]
    resources :categories do 
      resources :words
    end
  end
  root "pages#home"
  get '/about', to:'pages#about'
  get '/contact', to:'pages#contact'
  resources :users
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'
  
  resources :sessions, only: :create
  resources :lessons do
    resources :answers
  end
  resources :users do
    member do
      get :following, :followers, :words_learned
    end
  end
  
  resources :relationships, only: [:create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :words, dependent: :destroy
  has_many :lessons, dependent: :destroy
  validates :title,presence: true
  validates :description,presence: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :admin_user, only: :home
  before_action :logged_in_user
  def new
    @category=Category.new
  end
  def create
    @category = Category.new(category_params)
     if @category.save
      flash[:success] = "Successfully Created account"
      redirect_to admin_categories_path
     else
      render "new"
     end
  end
  def index
    @categories =Category.paginate(page: params[:page], per_page: 10).order(created_at: :desc)
  end

  def edit
    @category=Category.find(params[:id])
  end
  def update
    @category=Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = "Category Updated"
      redirect_to admin_categories_path
    else
      render 'edit'
    end
  end
  def destroy
    @category=Category.find(params[:id])
    @category.destroy
    redirect_to admin_categories_path
  end
  private
  def category_params
    params.require(:category).permit(:title, :description)
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/admin/categories/_form.html.erb
<%= form_with(model: [:admin, @category], local:true) do |f| %>
    <%= render "share/error_message", object: f.object %>
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control mb-2", placeholder: "Enter Title" %>
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control mb-2", placeholder: "Enter description" %>  
    <%= f.submit submit_name,class:"btn btn-primary btn-block" %>
<% end %>

app/views/admin/categories/edit.html.erb
<%= provide(:title,"Create category") %>

<h1 class="text-center">Create category</h1>

<div class="row">
    <div class="col-3">
    </div>
    <div class="col-6">
        <%= render "form", submit_name:"Save" %>
    </div>
    <div class="col-3">
    </div>
</div>

app/views/admin/categories/index.html.erb
<div class="row">
    <div class="col-2">
        <div class="card">
            <%= render "share/admin_side" %>
        </div>
    </div>
    <div class="col-10">
        <div class="card">
            <div class="card-header" style="justify-content:space-between;display:flex;"><p>Over View</p><%= link_to "New category", new_admin_category_path, class: "btn btn-success"%></div>
            <div class="card-body">
                <div class="row">
                    <table class="table">
                        <tr>
                            <th>Title</th>
                            <th>Description</th>
                            <th>Created at</th>
                            <th>actions</th>
                        </tr>
                    
                        <% @categories.each do |category| %>
                            <tr>
                                <td><%= link_to category.title, admin_category_words_path(category) %></td>
                                <td><%= category.description %></td>
                                <td><%= category.created_at.to_date %></td>
                                <td><%= link_to "Edit", edit_admin_category_path(id: category), class: "btn btn-success btn-block" %></td>
                                <td><%= link_to "Delete", admin_category_path(id: category), method: :delete, class: "btn btn-secondary btn-block" %></td>
                            </tr>
                        <% end %>
                    
                    </table>
                    <div class="mb-3" style="margin:auto;">
                        <%= will_paginate @categories %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/admin/categories/new.html.erb
<%= provide(:title,"Create category") %>
<h1 class="text-center">Create category</h1>

<div class="row">
    <div class="col-3">
    </div>
    <div class="col-6">
        <%= render "form", submit_name:"Save" %>
    </div>
    <div class="col-3">
    </div>
</div>